create table public.featured_trailers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "bunnyCDNVideoId" character varying null,
  "tmdbId" character varying null,
  slug character varying null,
  casts character varying[] null,
  "backdropUrl" character varying null,
  "posterUrl" character varying null,
  "thumbnailUrl" character varying null,
  title character varying null,
  description character varying null,
  constraint featured_trailers_pkey primary key (id)
) TABLESPACE pg_default;